--- #YAML:1.0
name:                Module-Release-Git
version:             0.10_01
abstract:            Use Git instead of CVS with Module::Release
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Module::Release:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - brian d foy <bdfoy@gmail.com>
