--- #YAML:1.0
name:                Module-Release-Git
version:             0.10_06
abstract:            Use Git instead of CVS with Module::Release
license:             perl
author:              
    - brian d foy <bdfoy@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Module::Release:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
