---
abstract: 'Use Git instead of CVS with Module::Release'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  Module::Release: 2.06
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Release-Git
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  x_Repository: https://github.com/briandfoy/module-release-git
version: 0.18
