---
abstract: 'Use Git instead of CVS with Module::Release'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
keywords:
  - workflow
  - module
  - distribution
  - pause
  - automation
  - testing
  - git
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Release-Git
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/briandfoy/module-release-git
version: 1.01
